### PR TITLE
Add oibrocevic to travis e-mail notification.

### PR DESCRIPTION
**Pull request by oibrocevic**
Test der Travis Integration und des Merge Ablaufs.

### CODE REVIEW

**Comment by agutenkunst** [comment]
@SansoneG Please check failing build https://travis-ci.org/PilzDE/psen_scan/jobs/616656123

**Comment by SansoneG** [comment]
@agutenkunst Merge should be possible now.

**Review by agutenkunst — APPROVED** [review]

**Review by agutenkunst — APPROVED** [review]

**Review by agutenkunst — APPROVED** [review]

**Comment by saheinisch** [comment]
Everything is fine.

**Review by saheinisch — APPROVED** [review]
Everything is OK.

**Pull request merged**
